import { preamble, type PromptContext } from './shared';

// Stage C — the NRT grid. A fundamentally different task from the narrative
// pass: this is transcribing a dictated checklist whose readings are terse, are
// interleaved with the hand-position script, and mean nothing out of slot order.
// Sharing a prompt with the narrative stage meant this guidance competed for
// attention with everything else; alone, it can be as specific as the grid is.
export function nrtPrompt(ctx: PromptContext): string {
  return [
    preamble(ctx),
    '',
    'Extract ONLY the NRT test findings in this pass. Ignore client symptoms,',
    'supplements, and follow-ups — they are extracted separately.',
    '',
    'This pass covers TWO different things, and they are read differently.',
    '',
    '(1) THE STRESSORS — a list, and the reason the appointment happens. These are',
    'often NOT announced as readings. They surface in ordinary talk, spread over',
    'several turns, introduced by a pronoun with no noun in sight: "so it is showing',
    'to be ___", "what your body responds to is ___", "that\'s ___". The word',
    '"stressor" itself is frequently never spoken. Read for the MEANING — the',
    'practitioner has just tested for what is stressing something and is saying what',
    'came up — not for a keyword.',
    'The narrowing usually arrives a turn or two later ("let\'s see if it\'s a specific',
    'food"), and so does its answer, which may be that there ISN\'T one ("it\'s not',
    'anything specific"). Read to the end of that exchange before writing the entry:',
    'the category and its source are often two turns apart, and stopping at the first',
    'gives you half the finding.',
    '',
    '(2) THE PROMPT GRID — the fixed list of muscle-testing prompts the practitioner',
    'works down, calling out a result for some of them. Fill ONLY the prompts a result',
    'was actually called for. Most sessions leave most slots empty; that is the normal,',
    'correct outcome.',
    '',
    '- nrt.pulse0: the Pulse 0 / pulse-point reading, verbatim as spoken.',
    '- nrt.priority1: the stated "Priority #1" finding.',
    '- nrt.k27: the K-27 (kidney-27 reflex point) result.',
    '- nrt.stressors: a LIST — one entry per stressor the practitioner identifies.',
    '    Locating the stressor is the point of the session, so this is the field to',
    '    read most carefully. Several are often named minutes apart, in passing, and',
    '    in ordinary conversation rather than as a called-out reading. Capture EVERY',
    '    one; do not keep only the last or merge them into a single entry.',
    '    Each entry has four parts:',
    '      category  — one of: immune, food, chemical, metal, scar, emotional, other.',
    '                  Use "other" when the practitioner names a stressor that fits',
    '                  none of these, rather than forcing it into the nearest one.',
    '      source    — the SPECIFIC thing named: the actual food, the actual chemical,',
    '                  the actual metal, which scar, what the emotional stress was.',
    '                  This is the part that gets missed. A category on its own is',
    '                  half a finding, so whenever the practitioner goes on to name',
    '                  what it actually is, record it here.',
    '                  Leave it null when they name the category and NOT the thing —',
    '                  saying it is food "but nothing specific" is a real finding, and',
    '                  filling in a plausible food is a fabricated clinical result.',
    '      body_area — the organ, gland or region it tested against, when stated.',
    '      detail    — the practitioner\'s own words about this stressor, when they',
    '                  say more than the three fields above hold.',
    '- nrt.foundation: the foundation muscle-testing pass, prompt by prompt:',
    '    laying1 = "LAYING 1 FOUNDATIONS", standing = "STANDING FOUNDATIONS",',
    '    hta = "HTA", hta_post_run = "HTA POST RUN", laying2 = "LAYING 2 FOUNDATIONS",',
    '    art_open = ART "OPEN", art_switch = ART "SWITCH", art_cns = ART "CNS",',
    '    art_dental = ART "DENTAL", art_hormonal = ART "HORMONAL",',
    '    additional = any foundation finding that fits none of the above.',
    '- nrt.body_scan: the body-scan pass, prompt by prompt. TWO SEPARATE testing rounds:',
    '    ART W/ POL → art_ectoderm ("ECTODERM"), art_priority ("PRIORITY"),',
    '      art_matrix ("MATRIX"), art_cell ("CELL"), additional_art ("ADDITIONAL ART"),',
    '    NRT W/O POL → scan_priority ("PRIORITY"), scan_matrix ("MATRIX"),',
    '      scan_cell ("CELL"), additional_nrt ("ADDITIONAL NRT").',
    '  Do not copy an ART reading into the NRT round or vice versa — they are separate',
    '  tests and the practitioner compares them. If you cannot tell which round a',
    '  reading belongs to, put it in additional_art or additional_nrt rather than',
    '  guessing a slot. A reading in the wrong slot is worse than one in ADDITIONAL.',
    '',
    '  WHICH ROUND a reading belongs to is decided by what the practitioner announced,',
    '  NOT by the reading name. "PRIORITY", "MATRIX" and "CELL" exist in BOTH rounds,',
    '  so the name alone tells you nothing. Track which round is running: an ART round',
    '  starts when the practitioner says so (ART, polarity, "with pol"). Until that',
    '  happens you are in the NRT (w/o pol) round.',
    '  If the session never announces an ART round, EVERY art_* slot stays null — a',
    '  test that was not performed has no result, and inventing one is worse than an',
    '  empty grid. Filling art_priority with a reading spoken in the NRT round is the',
    '  exact mistake this paragraph exists to prevent.',
    '',
    'In the GRID, record ONLY the result, never the prompt name: "negative", not "HTA',
    'is negative" and never just "HTA". A value that only repeats the prompt name is a',
    'blank — leave it null.',
  ].join('\n');
}
